insert into category values
	(default, 'other'),
	(default, 'grain'),
	(default, 'vegetable'),
	(default, 'fruit'),
	(default, 'sweetener'),
	(default, 'spice'),
	(default, 'seasoning'),
	(default, 'herb'),
	(default, 'fermented'),
	(default, 'protein'),
	(default, 'starch'),
	(default, 'fat'),
	(default, 'milk'),
	(default, 'sauce'),
	(default, 'bread'),
	(default, 'drink');

insert into ingredient values 
	(default, 'Cabbage', 3),
	(default, 'Bagel', 15),
	(default, 'Quail', 10),
	(default, 'Grapes', 4),
	(default, 'Wine', 16),
	(default, 'White Truffle Oil', 12),
	(default, 'Butternut Squash', 3),
	(default, 'Shiitake Mushroom', 10),
	(default, 'Veal', 10),
	(default, 'Raisins', 4),
	(default, 'Water', 16),
	(default, 'Tomato', 3),
	(default, 'Smoked Ham', 10),
	(default, 'Shrimp', 10),
	(default, 'Baguette', 15),
	(default, 'Broccoli', 3),
	(default, 'Peanut Oil', 12),
	(default, 'Chocolate', 5),
	(default, 'Beef', 10),
	(default, 'Bacon', 10),
	(default, 'Linguini Pasta', 2),
	(default, 'Gatorade', 16),
	(default, 'Yogurt', 13),
	(default, 'Coffee', 16),
	(default, 'Strawberry Jam', 5),
	(default, 'Honey Dew Melon', 4),
	(default, 'Crackers', 2),
	(default, 'Bean Sprouts', 3),
	(default, 'Banana', 4),
	(default, 'Balsamic Viniagrette', 14),
	(default, 'Apple', 4),
	(default, 'Green Tea', 16),
	(default, 'Radish', 3),
	(default, 'Pita Bread', 15),
	(default, 'Sorrano Pepper', 3),
	(default, 'Tomato Puree', 14),
	(default, 'Sunflower Oil', 12),
	(default, 'Mascarpone', 13),
	(default, 'Beer', 16),
	(default, 'Sage', 9),
	(default, 'Pork', 10),
	(default, 'Scallops', 10),
	(default, 'Sesame Thai Dressing', 14),
	(default, 'Black Tea', 16),
	(default, 'Energy Drink', 16),
	(default, 'Pine Nuts', 11),
	(default, 'Cranberry Juice', 16),
	(default, 'Italian Bread', 15),
	(default, 'Yucca', 3),
	(default, 'Rice', 2),
	(default, 'Oats', 2),
	(default, 'Flour', 2),
	(default, 'Teff', 2),
	(default, 'Quinoa', 2),
	(default, 'White Sugar', 5),
	(default, 'Brown Sugar', 5),
	(default, 'Cane Sugar', 5),
	(default, 'Agave Syrup', 5),
	(default, 'Stevia', 5),
	(default, 'Maple Syrup', 5),
	(default, 'Carrot', 3),
	(default, 'Kale', 3),
	(default, 'Spinach', 3),
	(default, 'Swiss Chard', 3),
	(default, 'Dairy Milk', 13),
	(default, 'Almond Milk', 13),
	(default, 'Oat Milk', 13),
	(default, 'Cashew Milk', 13),
	(default, 'Mango', 4),
	(default, 'Pineapple', 4),
	(default, 'Strawberry', 4),
	(default, 'Blueberry', 4);
	
insert into user_role values
	(1, 'User'),
	(2, 'Employee');